services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
  
  task-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: task-api
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules